import {
  Image,
  Shrink,
  Pipette,
  Crop,
  Video,
  Film,
  FileImage,
  FileText,
  FileType,
  Merge,
  FileJson,
  Regex,
  Clock,
  Binary,
  QrCode,
  KeyRound,
} from 'lucide-react';

export type ToolCategory = 'image' | 'video' | 'pdf' | 'dev' | 'other';

export interface Tool {
  /** Full title key — used on the home page */
  titleKey: string;
  /** Short title key — used on the tools listing page */
  shortTitleKey: string;
  descKey: string;
  icon: React.ComponentType<{ className?: string }>;
  href: string;
  category: ToolCategory;
  /** Single-color class for list view (e.g. `text-blue-500`) */
  color: string;
  /** Accent background class for card view */
  accentClass: string;
  /** Accent text class for card view */
  textClass: string;
  isNew?: boolean;
  comingSoon?: boolean;
}

export const tools: Tool[] = [
  {
    titleKey: 'tools.imageConverter.title',
    shortTitleKey: 'tools.imageConverter.shortTitle',
    descKey: 'tools.imageConverter.description',
    icon: Image,
    href: '/tools/image-converter',
    category: 'image',
    color: 'text-blue-500',
    accentClass: 'bg-blue-50 dark:bg-blue-950',
    textClass: 'text-blue-600 dark:text-blue-400',
  },
  {
    titleKey: 'tools.imageCompressor.title',
    shortTitleKey: 'tools.imageCompressor.shortTitle',
    descKey: 'tools.imageCompressor.description',
    icon: Shrink,
    href: '/tools/image-compressor',
    category: 'image',
    color: 'text-green-500',
    accentClass: 'bg-emerald-50 dark:bg-emerald-950',
    textClass: 'text-emerald-600 dark:text-emerald-400',
  },
  {
    titleKey: 'tools.colorPicker.title',
    shortTitleKey: 'tools.colorPicker.shortTitle',
    descKey: 'tools.colorPicker.description',
    icon: Pipette,
    href: '/tools/color-picker',
    category: 'image',
    color: 'text-pink-500',
    accentClass: 'bg-purple-50 dark:bg-purple-950',
    textClass: 'text-purple-600 dark:text-purple-400',
  },
  {
    titleKey: 'tools.imageCropper.title',
    shortTitleKey: 'tools.imageCropper.shortTitle',
    descKey: 'tools.imageCropper.description',
    icon: Crop,
    href: '/tools/image-cropper',
    category: 'image',
    color: 'text-amber-500',
    accentClass: 'bg-amber-50 dark:bg-amber-950',
    textClass: 'text-amber-600 dark:text-amber-400',
  },
  {
    titleKey: 'tools.videoConverter.title',
    shortTitleKey: 'tools.videoConverter.shortTitle',
    descKey: 'tools.videoConverter.description',
    icon: Video,
    href: '/tools/video-converter',
    category: 'video',
    color: 'text-violet-500',
    accentClass: 'bg-violet-50 dark:bg-violet-950',
    textClass: 'text-violet-600 dark:text-violet-400',
  },
  {
    titleKey: 'tools.videoCompressor.title',
    shortTitleKey: 'tools.videoCompressor.shortTitle',
    descKey: 'tools.videoCompressor.description',
    icon: Film,
    href: '/tools/video-compressor',
    category: 'video',
    color: 'text-emerald-500',
    accentClass: 'bg-blue-50 dark:bg-blue-950',
    textClass: 'text-blue-600 dark:text-blue-400',
  },
  {
    titleKey: 'tools.pdfToImage.title',
    shortTitleKey: 'tools.pdfToImage.shortTitle',
    descKey: 'tools.pdfToImage.description',
    icon: FileImage,
    href: '/tools/pdf-to-image',
    category: 'pdf',
    color: 'text-red-500',
    accentClass: 'bg-red-50 dark:bg-red-950',
    textClass: 'text-red-600 dark:text-red-400',
  },
  {
    titleKey: 'tools.imageToPdf.title',
    shortTitleKey: 'tools.imageToPdf.shortTitle',
    descKey: 'tools.imageToPdf.description',
    icon: FileText,
    href: '/tools/image-to-pdf',
    category: 'pdf',
    color: 'text-orange-500',
    accentClass: 'bg-orange-50 dark:bg-orange-950',
    textClass: 'text-orange-600 dark:text-orange-400',
  },
  {
    titleKey: 'tools.pdfToText.title',
    shortTitleKey: 'tools.pdfToText.shortTitle',
    descKey: 'tools.pdfToText.description',
    icon: FileType,
    href: '/tools/pdf-to-text',
    category: 'pdf',
    color: 'text-teal-500',
    accentClass: 'bg-teal-50 dark:bg-teal-950',
    textClass: 'text-teal-600 dark:text-teal-400',
  },
  {
    titleKey: 'tools.pdfMergeSplit.title',
    shortTitleKey: 'tools.pdfMergeSplit.shortTitle',
    descKey: 'tools.pdfMergeSplit.description',
    icon: Merge,
    href: '/tools/pdf-merge-split',
    category: 'pdf',
    color: 'text-indigo-500',
    accentClass: 'bg-indigo-50 dark:bg-indigo-950',
    textClass: 'text-indigo-600 dark:text-indigo-400',
  },
  {
    titleKey: 'tools.jsonFormatter.title',
    shortTitleKey: 'tools.jsonFormatter.shortTitle',
    descKey: 'tools.jsonFormatter.description',
    icon: FileJson,
    href: '/tools/json-formatter',
    category: 'dev',
    color: 'text-yellow-500',
    accentClass: 'bg-yellow-50 dark:bg-yellow-950',
    textClass: 'text-yellow-600 dark:text-yellow-400',
  },
  {
    titleKey: 'tools.regexTester.title',
    shortTitleKey: 'tools.regexTester.shortTitle',
    descKey: 'tools.regexTester.description',
    icon: Regex,
    href: '/tools/regex',
    category: 'dev',
    color: 'text-cyan-500',
    accentClass: 'bg-cyan-50 dark:bg-cyan-950',
    textClass: 'text-cyan-600 dark:text-cyan-400',
  },
  {
    titleKey: 'tools.timestampConverter.title',
    shortTitleKey: 'tools.timestampConverter.shortTitle',
    descKey: 'tools.timestampConverter.description',
    icon: Clock,
    href: '/tools/timestamp',
    category: 'dev',
    color: 'text-purple-500',
    accentClass: 'bg-purple-50 dark:bg-purple-950',
    textClass: 'text-purple-600 dark:text-purple-400',
    isNew: true,
  },
  {
    titleKey: 'tools.base64.title',
    shortTitleKey: 'tools.base64.shortTitle',
    descKey: 'tools.base64.description',
    icon: Binary,
    href: '/tools/base64',
    category: 'dev',
    color: 'text-orange-500',
    accentClass: 'bg-orange-50 dark:bg-orange-950',
    textClass: 'text-orange-600 dark:text-orange-400',
  },
  {
    titleKey: 'tools.qrcode.title',
    shortTitleKey: 'tools.qrcode.shortTitle',
    descKey: 'tools.qrcode.description',
    icon: QrCode,
    href: '/tools/qrcode',
    category: 'other',
    color: 'text-indigo-500',
    accentClass: 'bg-indigo-50 dark:bg-indigo-950',
    textClass: 'text-indigo-600 dark:text-indigo-400',
  },
  {
    titleKey: 'tools.passwordGenerator.title',
    shortTitleKey: 'tools.passwordGenerator.title',
    descKey: 'tools.passwordGenerator.description',
    icon: KeyRound,
    href: '#',
    category: 'other',
    color: 'text-red-500',
    accentClass: 'bg-red-50 dark:bg-red-950',
    textClass: 'text-red-600 dark:text-red-400',
    comingSoon: true,
  },
];
